config/routes.rb
Ketsie::Application.routes.draw do
  
  resources :posts do
    resources :comments
    resources :images
  end
  
  resources :user_infos
  resources :followers
  
  get 'images/image' => 'images#image'
  get 'userInfos/avatar' => 'user_infos#avatar'
  get 'user_infos/:post_id/destroyAvatar' => 'user_infos#destroy_avatar'
  get 'posts/like/:post_id' => 'posts#like'
    
  get "home/index"
  devise_for :users
  root :to => "home#index"
  

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  before_action :authenticate_user!
  
  def index   
    @current_post = nil
    
    @current_user = current_user     
    if @current_user.user_info == nil
      @current_user.user_info = UserInfo.new
    end
    @posts = current_user.posts.all.to_a
    
    @followed_users = current_user.followed_users.all    
    @followed_users.each do |user|
      user.posts.each do |post|
        @posts.push(post) if !post.text.nil?
      end
    end    
    
    @posts.sort! { |a,b| b.updated_at <=> a.updated_at }
    @likeable = Hash.new
    @liked_by = Hash.new
    @posts.each do |post|     
      @current_post = post if @current_post.nil?     
      @likeable[post.id] = ((Like.find_by(post_id: post.id, user_id: current_user.id))?false:true);      
      @likes = Like.where(post_id: post.id)
      if @likes
        @liked_by[post.id] = Array.new       
        @likes.each do |like|
          @liked_by[post.id].push(like.user)
        end       
      end       
    end
    
    if(params[:post_id])
      @current_post = params[:post_id]
    end
    
    @new_post = current_user.posts.new
    @current_post = Post.new if @current_post.nil?  
      
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_followed.html.erb
<% if !@followed.nil? %>
 <% @followed.each do |user| %>
<%= (t 'home.following', scope: :custom) %>:
<br />
    <p>	
    	<%= user.screenname %> <b><%= link_to (t 'home.unfollow', scope: :custom), "/followers/"+user.id.to_s, method: :delete, data: { confirm: (t 'home.unfollow_confirm', scope: :custom) } %>  </b>       
      <br /> 
    </p>
 <% end %>
<% end %>

app/views/home/_following.html.erb
<% if !@following.nil? %>
 <% @following.each do |user| %>
<%= t 'home.followed_by', scope: :custom %> 
<br />
    <p>	
    	<%= user.screenname %>      		               		 		               
      <br /> 
    </p>
 <% end %>
<% end %>

app/views/home/index.html.erb
<% content_for :images_section do %>
<% end %>

<% content_for :comments_section do %>
<% end %>

<% content_for :posts_section do %>
	<%= render "posts/form" %>
	<%= render @posts %>
<% end %>

<%= render template: "layouts/main_panels" %>

app/views/home/old_index.html.erb
<h1><%= t 'home.intro', scope: :custom %></h1>

<% if current_user %> 
   <%= t 'home.welcome', scope: :custom %>, <%= current_user.email %><br />
   sn: <%= current_user.screenname %><br />                 
<% end %>

<%= render "followed" %>

<%= render "following" %>

<br />

<br />

<%= link_to((t 'home.wall', scope: :custom), posts_path) %>
<br />
<%= link_to((t 'home.new_post', scope: :custom), new_post_path) %>
<br />
<%= link_to((t 'home.follow', scope: :custom), new_follower_path) %>       