config/routes.rb
Ketsie::Application.routes.draw do
  
  resources :posts do
    resources :comments
    resources :images
  end
  
  resources :user_infos
  resources :followers
  
  get 'images/image' => 'images#image'
  get 'userInfos/avatar' => 'user_infos#avatar'
  get 'user_infos/:post_id/destroyAvatar' => 'user_infos#destroy_avatar'
  get 'posts/like/:post_id' => 'posts#like'
    
  get "home/index"
  devise_for :users
  root :to => "home#index"
  

  

end

app/views/layouts/_header.html.erb
<header>
	<div id='header_wrapper'>
		<section class='link' id='main_logo'></section>
		<section id='search_field'>
			<span><%= search_field(:post, :search) %></span><span><%= search_field(:fake, :bg)%></span>
		</section>
		<section id='top_menu'>
			<% if user_signed_in? %>
				<ul id='ul_top_menu'>
					<li id='currentuser_screenname' class='link'>		
						<%= @current_user.screenname %>
					</li>
					<li id='currentuser_avatar' class='link'>					
			  			<%= render partial: "user_infos/show_avatar", locals: {user_info: @current_user.user_info } %>
					</li>
				</ul>				
			<% end %>
		</section>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ketsie - Spread your word!</title>
  <%= favicon_link_tag 'k_logo.ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>  
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>  
  <%= csrf_meta_tags %>
</head>
<body class="<%= "#{params[:controller]}_#{params[:action]}" %>">	
	
<!-- 	
	<p class="navbar-text pull-right">
	<%= link_to (t 'layouts.english', scope: :custom), "?locale=en", :class => 'navbar-link' %>
	<%= link_to (t 'layouts.czech', scope: :custom), "?locale=cs", :class => 'navbar-link' %>//
	<% if user_signed_in? %>
	  <%= t 'layouts.logged_in_as', scope: :custom %> <strong><%= current_user.screenname %> (<%= current_user.email %>)</strong>.
	  <%= link_to (t 'layouts.edit_profile', scope: :custom), edit_user_registration_path, :class => 'navbar-link' %> |
	  <%= link_to (t 'layouts.edit_user_information', scope: :custom), edit_user_info_path(:id => current_user.id), :class => 'navbar-link' %> |
	  <%= link_to (t 'layouts.logout', scope: :custom), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
	<% else %>
	  <%= link_to (t 'layouts.sign_up', scope: :custom), new_user_registration_path, :class => 'navbar-link'  %> |
	  <%= link_to (t 'layouts.login', scope: :custom), new_user_session_path, :class => 'navbar-link'  %>
	<% end %>
	</p>
-->	
	
	<div id="main_content">
		<% if notice %>
		  <p class="alert alert-notice"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-error"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
	<%= render "layouts/header" %>	
</body>
</html>

app/views/layouts/main_panels.html.erb
<section id='images_section'>
	<div id='images_fixed'>
		<%= yield :images_section %>
	</div>
</section>


<section id='posts_section'>
	<%= yield :posts_section %>
</section>


<section id='comments_section'>
	<div id='comments_fixed'>
		<%= yield :comments_section %>
	</div>
</section>